Bookmark crud
aliu19/fse-sp22-tuiter-server-node pull request #12
Opened 2022-04-25 22:18 UTC by aliu19

2022-04-25 22:30 UTC, caijiah requested changes
Need a minor change.

2022-04-25 22:30 UTC, caijiah commented on controllers/BookmarkController.ts
> +                BookmarkController.bookmarkDao.findAllTuitsBookmarkedByUser(userId)
Hey Andrew, we need a minor change here that we need populate "postedBy" for these tuits.

2022-04-25 22:57 UTC, caijiah approved these changes
Nice work! Thanks

2022-04-26 01:27 UTC, averywpx approved these changes

2022-04-26 01:29 UTC, merged